### ISSUE TITLE
admin bitvalues?

### ISSUE THREAD

**Issue by 2WR3505** [videoP/jaPRO#24]
wavin a hand to the dev, what are the admin bitvalues for japro?

**Comment by sithmartyr** [comment]
> wavin a hand to the dev, what are the admin bitvalues for japro?

You use the toggleAdmin and tweakAdmin commands in the console to change the bitvalues for admin permissions.

**Comment by 2WR3505** [comment]
ah, so you set custom bitvalues?

edit: that doesnt seem to work right, it only disables or enables amtele, and it doesnt really give any kind of value, tweakadmin doesnt do squat

**Comment by sithmartyr** [comment]
Toggling the admin commands that are enabled using toggleAdmin will change the bitvalue of the g_fullAdminLevel or g_juniorAdminLevel cvars. 
Once you toggle an admin command on or off, you will see that the value of those cvars will change. 

Yeah, tweakAdmin wasn't a usable command, but there are other commands like it for tweaking force powers or Saber stuff, thus "tweakSaber" and "tweakForce" can be used. I just couldn't remember if one of those style of commands existed for admin or not.

**Comment by 2WR3505** [comment]
whatever i try, it only toggles amtele, so yea, doesnt work, lol

**Comment by sithmartyr** [comment]
Here is the result when I use this command:

`rcon toggleadmin full
0 [X] Amtele
1 [X] Amfreeze
2 [x] Amban
3 [x] 
3 [x] 
3 [x] 
3 [x] 
3 [x] 
3 [x] 
3 [x] 
3 [x] 
3 [x] `

**Comment by sithmartyr** [comment]
> whatever i try, it only toggles amtele, so yea, doesnt work, lol

It sounds like you may be using the command incorrectly.
Below I've included a log of the input and output when I use the command:

]rcon toggleadmin full
 0 [X] Amtele    
 1 [X] Amfreeze  
 2 [X] Amtelemark
 3 [X] Amban
 4 [X] Amkick
 5 [X] NPC
 6 [X] Noclip
 7 [X] Grantadmin
 8 [X] Ammap
 9 [X] Ampsay
10 [X] Amforceteam
11 [X] Amlockteam
12 [X] Amvstr
13 [X] See IPs
14 [X] Amrename
15 [X] Amlistmaps
16 [ ] Amwhois
17 [ ] Amlookup
18 [ ] Use hide
19 [ ] See hiders
20 [ ] Callvote
21 [ ] Killvote
22 [ ] Read Amsay

You can then use _rcon toggleadmin full \<Insert Number\>_ to toggle an admin permission on/off for the specified admin level.
After you get the admin permissions set to the way you want, if you would like the bitvalue of the cvar, you can type _rcon g_fullAdminLevel_ or _rcon g_juniorAdminLevel_ to see the bitvalue of the cvar.
