### ISSUE TITLE
scoreboard ping display accuracy improvement from razor/daggo

### ISSUE THREAD

**Issue by videoP** [videoP/jaPRO#4]

**Comment by entdark** [comment]
No commits? :(

**Comment by videoP** [comment]
https://github.com/eternalcodes/EternalJK/commit/dce033b2714b1c0f8842e66c0e94ea82e6b6f506

**Comment by videoP** [comment]
> 
> 
> No commits? :(

https://github.com/eternalcodes/EternalJK/commit/dce033b2714b1c0f8842e66c0e94ea82e6b6f506
